# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1

      - name: Start deployment
        run: |
          npm install
          npm run build
          mv out /tmp
          cd /tmp
          git clone https://github.com/SavvasStephanides/savvas.git
          cd savvas
          rm -rf ./static/pouentouton
          mv /tmp/out ./static/pouentouton
          git status
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
   
          git add -A
          git commit -m "Automated Update PouEnTouton"
          git push --all -f https://${{ secrets.GH_TOKEN }}@github.com/SavvasStephanides/savvas.git
